import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "OVO - Digital Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="img/png" href="/logo.png" />
        <link
          rel="stylesheet"
          href={`https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap`}
        />
      </Head>
      <body>{children}</body>
    </html>
  );
}
